/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGraficasistema;

import sistema.control.ClienteControl;
import sistema.control.cadastroclientecontrol;

/**
 *
 * @author maicon
 */
public class Cadastrar extends javax.swing.JFrame {

    /**
     * Creates new form Cadastrar
     */
    public Cadastrar() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastroclientes = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jnome = new javax.swing.JTextField();
        jemail = new javax.swing.JTextField();
        jlimpar = new javax.swing.JButton();
        jcadastrar = new javax.swing.JButton();
        jsenhas = new javax.swing.JTextField();
        jSair = new javax.swing.JButton();
        jHOME = new javax.swing.JButton();
        jsenha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cadastroclientes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cadastroclientes.setText(" Cadastro de clientes");
        getContentPane().add(cadastroclientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, 20));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 60, 20));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("E-mail:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 60, -1));

        jnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnomeActionPerformed(evt);
            }
        });
        getContentPane().add(jnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 390, -1));

        jemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jemailActionPerformed(evt);
            }
        });
        getContentPane().add(jemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 390, -1));

        jlimpar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlimpar.setText("Limpar");
        jlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlimparActionPerformed(evt);
            }
        });
        getContentPane().add(jlimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

        jcadastrar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jcadastrar.setText("Cadastrar");
        jcadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jcadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, -1, -1));

        jsenhas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsenhasActionPerformed(evt);
            }
        });
        getContentPane().add(jsenhas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 390, -1));

        jSair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jSair.setText("Sair");
        jSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSairActionPerformed(evt);
            }
        });
        getContentPane().add(jSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        jHOME.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jHOME.setText("Home");
        jHOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHOMEActionPerformed(evt);
            }
        });
        getContentPane().add(jHOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        jsenha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jsenha.setText("Senha:");
        getContentPane().add(jsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnomeActionPerformed

    private void jemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jemailActionPerformed

    private void jlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlimparActionPerformed
        //limpar posicao mandar vazio
        jnome.setText("");
        jemail.setText("");
        jsenha.setText("");
        
        //  jid.setText("");

    }//GEN-LAST:event_jlimparActionPerformed

    private void jcadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcadastrarActionPerformed
        //evento cadastrar
        String nome = jnome.getText();
        String email = jemail.getText();
        String senha=jsenha.getText();
        
       // String endereco = jendereco.getText();
      ///  String telefone = jtelefone.getText();
      //  String cidade = jcidade.getText();
     //   String estado = jestado.getText();
        //   String id=jid.getText();

        cadastroclie.Inserecadastro(nome, email,senha);
    }//GEN-LAST:event_jcadastrarActionPerformed

    private void jsenhasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsenhasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jsenhasActionPerformed

    private void jSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jSairActionPerformed

    private void jHOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHOMEActionPerformed

        //abrir nova tela
        new TelaLogin().setVisible(true);
        //fechar a tela
        this.dispose();
    }//GEN-LAST:event_jHOMEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastrar().setVisible(true);
            }
        });
    }
    cadastroclientecontrol cadastroclie = new cadastroclientecontrol();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cadastroclientes;
    private javax.swing.JButton jHOME;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jSair;
    private javax.swing.JButton jcadastrar;
    private javax.swing.JTextField jemail;
    private javax.swing.JButton jlimpar;
    private javax.swing.JTextField jnome;
    private javax.swing.JLabel jsenha;
    private javax.swing.JTextField jsenhas;
    // End of variables declaration//GEN-END:variables
}
