/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGraficasistema;

import Agendabancodades.Contato;
import DAO.contatoDAO;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maicon
 */
public class TelaInicial extends javax.swing.JFrame {
    
    DefaultTableModel tmContato = new DefaultTableModel(null, new String[]{"id", "nome", "endereco", "telefone"});
    //listar todas
    List<Contato> contatos;
    ListSelectionModel slmContato;

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        habilidadados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jpesquisar = new javax.swing.JTextField();
        jBotaopesquisar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jid = new javax.swing.JLabel();
        jnome = new javax.swing.JLabel();
        jendereco = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jtelefone = new javax.swing.JLabel();
        jemail = new javax.swing.JLabel();
        jsexo = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jnovo = new javax.swing.JButton();
        alterar = new javax.swing.JButton();
        jexcluir = new javax.swing.JButton();
        jsalvar = new javax.swing.JButton();
        jsair = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTtabela = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBotaopesquisar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBotaopesquisar.setText("Pesquisar");
        jBotaopesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaopesquisarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Dados de contato");

        jid.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jid.setText("Id:");

        jnome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jnome.setText("Nome:");

        jendereco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jendereco.setText("Endereço:");

        jtelefone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtelefone.setText("Telefone:");

        jemail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jemail.setText("Email:");

        jsexo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jsexo.setText("Sexo:");

        jnovo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jnovo.setText("Novo");
        jnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnovoActionPerformed(evt);
            }
        });

        alterar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        alterar.setText("Alterar");
        alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarActionPerformed(evt);
            }
        });

        jexcluir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jexcluir.setText("Excluir");
        jexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jexcluirActionPerformed(evt);
            }
        });

        jsalvar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jsalvar.setText("Salvar");
        jsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsalvarActionPerformed(evt);
            }
        });

        jsair.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jsair.setText("Sair");
        jsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsairActionPerformed(evt);
            }
        });

        jTtabela.setModel(tmContato);
        jTtabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        slmContato=jTtabela.getSelectionModel();
        slmContato.addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent e){
                if(! e.getValueIsAdjusting()){
                    jTtabelaLinhaSelecionada(jTtabela);
                }
            }
        });
        jScrollPane2.setViewportView(jTtabela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jpesquisar)
                                .addGap(18, 18, 18)
                                .addComponent(jBotaopesquisar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jnome)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jendereco, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jid)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField2)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                                            .addComponent(jTextField1))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(74, 74, 74)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jemail)
                                                    .addComponent(jsexo))
                                                .addGap(32, 32, 32))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jtelefone)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField4)
                                            .addComponent(jTextField5)
                                            .addComponent(jTextField6)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator1)))
                                .addGap(6, 6, 6))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jnovo)
                        .addGap(18, 18, 18)
                        .addComponent(alterar)
                        .addGap(18, 18, 18)
                        .addComponent(jexcluir)
                        .addGap(18, 18, 18)
                        .addComponent(jsalvar)
                        .addGap(18, 18, 18)
                        .addComponent(jsair)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBotaopesquisar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jid)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtelefone)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jnome)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jemail)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jendereco)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsexo)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jnovo)
                    .addComponent(alterar)
                    .addComponent(jexcluir)
                    .addComponent(jsalvar)
                    .addComponent(jsair))
                .addGap(66, 66, 66)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBotaopesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaopesquisarActionPerformed
        try {
            listarContatos();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro no batao pesquisar");
        }
    }//GEN-LAST:event_jBotaopesquisarActionPerformed

    private void alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alterarActionPerformed

    private void jnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnovoActionPerformed
        habilidadados();
        jnome.setText("");
        jemail.setText("");
        jendereco.setText("");
        jsexo.setText("");
        jtelefone.setText("");
        

    }//GEN-LAST:event_jnovoActionPerformed

    private void jsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsalvarActionPerformed
//testar mudanca codigo aqui

        if (verificaDados()) {
            cadastro();
            desabitilacampos();
        }

    }//GEN-LAST:event_jsalvarActionPerformed

    private void jexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jexcluirActionPerformed
        excluirContato();
        mostrarPesquisa(contatos);
        

    }//GEN-LAST:event_jexcluirActionPerformed

    private void jsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsairActionPerformed
      System.exit(0);
    }//GEN-LAST:event_jsairActionPerformed
    
    public void excluirContato() {
        int resposta = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir esse Contato?", "Confirmar", JOptionPane.YES_NO_CANCEL_OPTION);
        if (resposta == JOptionPane.YES_NO_OPTION) {
            contatoDAO dao = new contatoDAO();
            //dao.remove(contatos.get(jTtabela.getSelectedRow()));
            
        }
    }
    
    public void listarContatos() throws SQLException {
        contatoDAO dao = new contatoDAO();
        contatos = dao.getLista("%" + jBotaopesquisar.getText() + "%");
        
        mostrarPesquisa(contatos);
    }
    
    public void cadastro() {
        
        try {
            Contato contato = new Contato();
            contato.setNome(jnome.getText());
            contato.setEndereco(jendereco.getText());
            contato.setEmail(jemail.getText());
            contato.setTelefone(jtelefone.getText());
            contato.setSexo(jsexo.getText());
            
            contatoDAO dao = new contatoDAO();
            dao.adiciona(contato);
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    //para habilitar e desabilitar alguns campos especificos
    public void desabitilacampos() {
        // jid. setEditable(false);
        //  jnome.setEditable(façse);
        //jemail.setEditable(false);
        //jendereco.setEditable(false);
        //jsexo.setEditable(false);

    }
    
    public void habilidadados() {
        //jnome.setEditTable(true);

    }
    
    public boolean verificaDados() {
        if (!jnome.getText().equals("") && !jendereco.getText().equals("") && !jtelefone.getText().equals("")) {
            
            return true;
        } else {
            
            JOptionPane.showMessageDialog(null, "Usuario voce esqueceu de prencher algum campo");
            return false;
        }
    }
    
    private void jTtabelaLinhaSelecionada(JTable tabela) {
        if (jTtabela.getSelectedRow() != -1) {
            jid.setText(String.valueOf(contatos.get(tabela.getSelectedRow()).getId()));
            jnome.setText(String.valueOf(contatos.get(tabela.getSelectedRow()).getNome()));
            jtelefone.setText(String.valueOf(contatos.get(tabela.getSelectedRow()).getTelefone()));
            jendereco.setText(String.valueOf(contatos.get(tabela.getSelectedRow()).getEndereco()));
            jemail.setText(String.valueOf(contatos.get(tabela.getSelectedRow()).getEmail()));
            jsexo.setText(String.valueOf(contatos.get(tabela.getSelectedRow()).getSexo()));
        } else {
            jid.setText("");
            jnome.setText("");
            jendereco.setText("");
            jtelefone.setText("");
            jemail.setText("");
            jsexo.setText("");
            
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterar;
    private javax.swing.JButton jBotaopesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTable jTtabela;
    private javax.swing.JLabel jemail;
    private javax.swing.JLabel jendereco;
    private javax.swing.JButton jexcluir;
    private javax.swing.JLabel jid;
    private javax.swing.JLabel jnome;
    private javax.swing.JButton jnovo;
    private javax.swing.JTextField jpesquisar;
    private javax.swing.JButton jsair;
    private javax.swing.JButton jsalvar;
    private javax.swing.JLabel jsexo;
    private javax.swing.JLabel jtelefone;
    // End of variables declaration//GEN-END:variables

    private void mostrarPesquisa(List<Contato> contatos) {
        //pega as listas selecionadas
        while (tmContato.getRowCount() > 0) {
            //remove as listas
            tmContato.removeRow(0);
            
        }
        
        if (contatos.size() == 0) {
            JOptionPane.showMessageDialog(null, "Nenhum contato cadastrado");
        } else {
            String[] linha = new String[]{null, null, null, null};
            for (int i = 0; i < contatos.size(); i++) {
                tmContato.addRow(linha);
                tmContato.setValueAt(contatos.get(i).getId(), i, 0);
                tmContato.setValueAt(contatos.get(i).getNome(), i, 1);
                tmContato.setValueAt(contatos.get(i).getEndereco(), i, 2);
                tmContato.setValueAt(contatos.get(i).getTelefone(), i, 3);
                
            }
        }
    }
}
